<?php
/**
 * This file generated by Zend\Expressive\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via zend-expressive-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Handler\AddressesCreateHandler::class => App\Handler\AddressesCreateHandlerFactory::class,
            App\Handler\AddressesDeleteHandler::class => App\Handler\AddressesDeleteHandlerFactory::class,
            App\Handler\AddressesReadHandler::class => App\Handler\AddressesReadHandlerFactory::class,
            App\Handler\AddressesUpdateHandler::class => App\Handler\AddressesUpdateHandlerFactory::class,
            App\Handler\UserAddressesCreateHandler::class => App\Handler\UserAddressesCreateHandlerFactory::class,
            App\Handler\UserReadHandler::class => App\Handler\UserReadHandlerFactory::class,
            App\Handler\UsersCreateHandler::class => App\Handler\UsersCreateHandlerFactory::class,
            App\Handler\UsersDeleteHandler::class => App\Handler\UsersDeleteHandlerFactory::class,
            App\Handler\UsersUpdateHandler::class => App\Handler\UsersUpdateHandlerFactory::class,
            App\Handler\UsersViewHandler::class => App\Handler\UsersViewHandlerFactory::class,
        ],
    ],
];
